import { mkdtemp, readFile, writeFile, mkdir, symlink, stat } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { cleanFile, createEngine, diffFile, planClean, scanFile } from "../src/cleaner/engine.js";
import { applyRemovals, preservedContent } from "../src/cleaner/applyRemovals.js";
import { inspectContent } from "../src/inspect/inspectContent.js";
import { assertSafePath, looksBinary } from "../src/utils/fsSafe.js";
import { AppError } from "../src/utils/types.js";
import { loadConfig } from "../src/config/loadConfig.js";
import { loadRules } from "../src/rules/loadRules.js";
import { validateTransformation } from "../src/validation/validate.js";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const fixtures = path.join(repoRoot, "fixtures");

async function withTempDir(): Promise<string> {
  const root = path.join(repoRoot, ".tmp");
  await mkdir(root, { recursive: true });
  return mkdtemp(path.join(root, "claude-clean-"));
}

function sampleDocument(watermarkLine: string): string {
  return [
    "# Project",
    "",
    "This document explains installation, usage, and troubleshooting for the sample project.",
    "Keep every paragraph that is not an attribution footer.",
    "",
    "## Installation",
    "",
    "npm install example-package",
    "",
    watermarkLine,
    "",
    "## Usage",
    "",
    "Run the tool against files you own. Surrounding sections must stay intact.",
    "",
  ].join("\n");
}

describe("detection and removal", () => {
  it("detects a watermark", async () => {
    const result = await scanFile(path.join(fixtures, "markdown-watermark.md"));
    expect(result.watermarks.length).toBeGreaterThan(0);
    expect(result.watermarks[0]?.matchedText).toMatch(/Generated by Claude/i);
  });

  it("removes a watermark and preserves surrounding content", async () => {
    const engine = await createEngine(repoRoot);
    const original = await readFile(path.join(fixtures, "markdown-watermark.md"), "utf8");
    const plan = planClean(engine, original, "doc.md", "markdown", { yes: true, confidence: 0.99 });
    expect(plan.cleaned).toContain("Hello world.");
    expect(plan.cleaned).toContain("## Usage");
    expect(plan.cleaned).not.toMatch(/Generated by Claude/i);
    expect(preservedContent(original, plan.cleaned, plan.removals)).toBe(true);
    expect(plan.cleaned).toBe(applyRemovals(original, plan.removals));
  });

  it("reports no watermark on a clean file", async () => {
    const result = await scanFile(path.join(fixtures, "markdown-clean.md"));
    expect(result.alreadyClean).toBe(true);
    expect(result.watermarks.filter((item) => item.action === "remove")).toHaveLength(0);
  });

  it("removes multiple watermarks", async () => {
    const engine = await createEngine(repoRoot);
    const original = await readFile(path.join(fixtures, "multiple.md"), "utf8");
    const plan = planClean(engine, original, "doc.md", "markdown", { yes: true, confidence: 0.9 });
    expect(plan.actionable.length).toBeGreaterThanOrEqual(2);
    expect(plan.cleaned).toContain("Body stays.");
    expect(plan.cleaned).not.toMatch(/Generated by Claude/i);
    expect(plan.cleaned).not.toMatch(/Made with Claude/i);
  });

  it("does not treat product discussion as a watermark", async () => {
    const result = await scanFile(path.join(fixtures, "false-positive.md"));
    expect(result.watermarks).toHaveLength(0);
  });
});

describe("markdown html json", () => {
  it("protects fenced code blocks", async () => {
    const engine = await createEngine(repoRoot);
    const original = await readFile(path.join(fixtures, "markdown-codeblock.md"), "utf8");
    const plan = planClean(engine, original, "doc.md", "markdown", { includeCode: false });
    expect(plan.cleaned).toContain('print("Generated by Claude")');
  });

  it("can include code when requested", async () => {
    const engine = await createEngine(repoRoot);
    const original = await readFile(path.join(fixtures, "markdown-codeblock.md"), "utf8");
    const plan = planClean(engine, original, "doc.md", "markdown", {
      includeCode: true,
      yes: true,
      confidence: 0.99,
    });
    expect(plan.cleaned).not.toContain("Generated by Claude");
  });

  it("removes html comments without dropping surrounding nodes", async () => {
    const engine = await createEngine(repoRoot);
    const original = await readFile(path.join(fixtures, "html-comment.html"), "utf8");
    const plan = planClean(engine, original, "page.html", "html", { yes: true, confidence: 0.99 });
    expect(plan.cleaned).toContain("<p>Hello</p>");
    expect(plan.cleaned).toContain("<p>World</p>");
    expect(plan.cleaned).not.toMatch(/generated by Claude/i);
  });

  it("modifies json through parse/inspect/serialize", async () => {
    const engine = await createEngine(repoRoot);
    const original = await readFile(path.join(fixtures, "json-attribution.json"), "utf8");
    const plan = planClean(engine, original, "data.json", "json", { yes: true, confidence: 0.99 });
    const parsed = JSON.parse(plan.cleaned) as { title: string; body: string; generated_by?: string };
    expect(parsed.title).toBe("Notes");
    expect(parsed.body).toBe("Useful text");
    expect(JSON.parse(original)).toEqual({
      title: "Notes",
      body: "Useful text",
      generated_by: "Generated by Claude",
    });
    expect(parsed.generated_by ?? "").not.toMatch(/Generated by Claude/i);
  });
});

describe("unicode and inspect", () => {
  it("detects a long zero-width run", async () => {
    const engine = await createEngine(repoRoot);
    const hidden = "\u200B".repeat(8);
    const original = `Visible${hidden}text`;
    const plan = planClean(engine, original, "doc.md", "text", { yes: true, confidence: 0.9 });
    expect(plan.actionable.length).toBeGreaterThan(0);
    expect(plan.cleaned).toBe("Visibletext");
  });

  it("does not auto-delete a single zero-width character", async () => {
    const engine = await createEngine(repoRoot);
    const original = `Visible\u200Btext`;
    const plan = planClean(engine, original, "doc.md", "text", {});
    expect(plan.cleaned).toBe(original);
    const findings = inspectContent(original, plan.detections);
    expect(findings.some((item) => item.kind === "zero-width")).toBe(true);
    expect(findings.every((item) => item.autoRemovable === false || item.kind !== "zero-width")).toBe(
      true,
    );
  });
});

describe("cli file behaviors", () => {
  it("writes a sidecar output file", async () => {
    const dir = await withTempDir();
    const input = path.join(dir, "README.md");
    await writeFile(input, sampleDocument("Generated by Claude"));
    const result = await cleanFile(input, { yes: true, confidence: 0.99 }, dir);
    expect(result.written).toBe(true);
    expect(result.outputPath).toBe(path.join(dir, "README.cleaned.md"));
    const cleaned = await readFile(result.outputPath!, "utf8");
    expect(cleaned).toContain("## Usage");
    expect(cleaned).not.toMatch(/Generated by Claude/i);
    const original = await readFile(input, "utf8");
    expect(original).toContain("Generated by Claude");
  });

  it("supports in-place mode", async () => {
    const dir = await withTempDir();
    const input = path.join(dir, "README.md");
    await writeFile(input, sampleDocument("Generated by Claude"));
    await cleanFile(input, { inPlace: true, yes: true, confidence: 0.99 }, dir);
    const cleaned = await readFile(input, "utf8");
    expect(cleaned).not.toMatch(/Generated by Claude/i);
  });

  it("creates a backup and refuses to overwrite it", async () => {
    const dir = await withTempDir();
    const input = path.join(dir, "README.md");
    const original = sampleDocument("Generated by Claude");
    await writeFile(input, original);
    await cleanFile(input, { backup: true, inPlace: true, yes: true, confidence: 0.99 }, dir);
    const backup = await readFile(`${input}.claude-clean.bak`, "utf8");
    expect(backup).toContain("Generated by Claude");
    await writeFile(input, original);
    await expect(
      cleanFile(input, { backup: true, inPlace: true, yes: true, confidence: 0.99 }, dir),
    ).rejects.toBeInstanceOf(AppError);
  });

  it("dry-run does not write", async () => {
    const dir = await withTempDir();
    const input = path.join(dir, "README.md");
    const original = sampleDocument("Generated by Claude");
    await writeFile(input, original);
    const result = await cleanFile(input, { dryRun: true, yes: true, confidence: 0.99 }, dir);
    expect(result.written).toBe(false);
    expect(await readFile(input, "utf8")).toBe(original);
  });

  it("diff does not modify the file", async () => {
    const dir = await withTempDir();
    const input = path.join(dir, "README.md");
    const original = sampleDocument("Generated by Claude");
    await writeFile(input, original);
    const result = await diffFile(input, {}, dir);
    expect(result.diff).toContain("Generated by Claude");
    expect(await readFile(input, "utf8")).toBe(original);
  });

  it("recursive mode processes nested files", async () => {
    const dir = await withTempDir();
    await mkdir(path.join(dir, "nested"), { recursive: true });
    await writeFile(path.join(dir, "nested", "a.md"), "Generated by Claude\nkeep\n");
    const { collectFiles } = await import("../src/utils/paths.js");
    const files = await collectFiles(dir, true);
    expect(files.some((file) => file.endsWith("a.md"))).toBe(true);
  });

  it("is idempotent", async () => {
    const dir = await withTempDir();
    const input = path.join(dir, "README.md");
    await writeFile(input, sampleDocument("Generated by Claude"));
    const first = await cleanFile(input, { yes: true, confidence: 0.99 }, dir);
    const second = await cleanFile(first.outputPath!, { yes: true, confidence: 0.99 }, dir);
    expect(second.alreadyClean).toBe(true);
    expect(second.written).toBe(false);
  });
});

describe("configuration and rules", () => {
  it("loads default config", async () => {
    const config = await loadConfig(repoRoot);
    expect(config.output.suffix).toBe(".cleaned");
  });

  it("loads a custom config and custom rules", async () => {
    const dir = await withTempDir();
    await writeFile(
      path.join(dir, ".claude-clean.yml"),
      `version: 1\nrules:\n  enabled: [custom]\n  extraDirs: [rules]\n`,
    );
    await mkdir(path.join(dir, "rules", "custom"), { recursive: true });
    await writeFile(
      path.join(dir, "rules", "custom", "example.json"),
      JSON.stringify({
        id: "custom-foo-watermark",
        provider: "custom",
        type: "watermark",
        match: { type: "literal", value: "FOO_WATERMARK" },
        confidence: 0.99,
        action: "remove",
        expandToLine: true,
      }),
    );
    const config = await loadConfig(dir);
    const rules = await loadRules(config.rules.enabled, [path.join(dir, "rules")]);
    expect(rules.some((rule) => rule.id === "custom-foo-watermark")).toBe(true);
  });
});

describe("safety", () => {
  it("rejects path traversal", () => {
    expect(() => assertSafePath("../outside.md", repoRoot)).toThrow(AppError);
  });

  it("rejects a null byte in a path", () => {
    expect(() => assertSafePath("file\0.md", repoRoot)).toThrow(AppError);
  });

  it("rejects binary files", () => {
    expect(looksBinary(Buffer.from([0, 1, 2, 3, 4, 0, 0]))).toBe(true);
  });

  it("rejects huge files", async () => {
    const dir = await withTempDir();
    const input = path.join(dir, "huge.md");
    await writeFile(input, "Generated by Claude\n");
    await expect(scanFile(input, { maxFileBytes: 4 }, dir)).rejects.toBeInstanceOf(AppError);
  });

  it("rejects malformed json", async () => {
    const engine = await createEngine(repoRoot);
    expect(() => planClean(engine, "{not json", "data.json", "json", { yes: true })).toThrow(AppError);
  });

  it("refuses unsafe deletion ratios", () => {
    expect(() =>
      validateTransformation("abcdefghij", "ab", "text", [{ start: 2, end: 10, replacement: "" }], 0.5),
    ).toThrow(AppError);
  });

  it("refuses symlinks", async () => {
    const dir = await withTempDir();
    const real = path.join(dir, "real.md");
    const link = path.join(dir, "link.md");
    await writeFile(real, "Generated by Claude\n");
    await symlink(real, link);
    await expect(scanFile(link, {}, dir)).rejects.toBeInstanceOf(AppError);
    expect((await stat(link)).isFile()).toBe(true);
  });
});
